version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-flowtype
    versions:
    - 5.2.0
    - 5.2.1
    - 5.2.2
    - 5.3.0
    - 5.3.1
    - 5.4.0
    - 5.5.0
    - 5.6.0
    - 5.7.0
    - 5.7.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/plugin-transform-react-constant-elements"
    versions:
    - 7.12.1
    - 7.12.13
    - 7.13.10
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-dev-utils
    versions:
    - 5.0.2
